// Azure Functions entry point — imports all function registrations
import './functions/populations.js'
import './functions/questionnaires.js'
import './functions/templates.js'
import './functions/simulations.js'
import './functions/chunk-processor.js'
import './functions/chunk-processor-poison.js'
import './functions/analytics.js'
import './functions/reference-data.js'
import './functions/ab-tests.js'
